inherit_from: .rubocop_todo.yml

require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "bin/*"

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
