    default: &default
      adapter: postgresql
      encoding: unicode
      host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
      port: <%= ENV.fetch('POSTGRES_PORT', 5432) %>
      pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
      username: postgres
      password: postgres

    development:
      <<: *default
      database: rtfm_guard_development

    test:
      <<: *default
      database: rtfm_guard_test

    production:
      url: <%= ENV['DATABASE_URL'] %>
